# Generated by Django 5.2.6 on 2025-09-21 10:58

import customers.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('date', models.DateField(blank=True, null=True)),
                ('photos_count', models.PositiveIntegerField(default=0)),
                ('selected_count', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_key', models.CharField(max_length=512)),
                ('thumbnail_key', models.CharField(blank=True, max_length=512, null=True)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('thumb_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('is_selected', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='customers.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, default=customers.models.generate_token, max_length=32, unique=True)),
                ('can_select', models.BooleanField(default=True)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_link', to='customers.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['owner', 'name'], name='customers_c_owner_i_0c182c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['customer', 'name'], name='customers_e_custome_4a4c88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('customer', 'name')},
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['event', 'created_at'], name='customers_p_event_i_f6e834_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['event', 'is_selected'], name='customers_p_event_i_8db34e_idx'),
        ),
    ]
