# Generated by Django 5.2.6 on 2025-09-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='photos_used_cached',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
